// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages-webauthn.proto

#ifndef PROTOBUF_INCLUDED_messages_2dwebauthn_2eproto
#define PROTOBUF_INCLUDED_messages_2dwebauthn_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2dwebauthn_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2dwebauthn_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_messages_2dwebauthn_2eproto();
namespace hw {
namespace trezor {
namespace messages {
namespace webauthn {
class WebAuthnAddResidentCredential;
class WebAuthnAddResidentCredentialDefaultTypeInternal;
extern WebAuthnAddResidentCredentialDefaultTypeInternal _WebAuthnAddResidentCredential_default_instance_;
class WebAuthnCredentials;
class WebAuthnCredentialsDefaultTypeInternal;
extern WebAuthnCredentialsDefaultTypeInternal _WebAuthnCredentials_default_instance_;
class WebAuthnCredentials_WebAuthnCredential;
class WebAuthnCredentials_WebAuthnCredentialDefaultTypeInternal;
extern WebAuthnCredentials_WebAuthnCredentialDefaultTypeInternal _WebAuthnCredentials_WebAuthnCredential_default_instance_;
class WebAuthnListResidentCredentials;
class WebAuthnListResidentCredentialsDefaultTypeInternal;
extern WebAuthnListResidentCredentialsDefaultTypeInternal _WebAuthnListResidentCredentials_default_instance_;
class WebAuthnRemoveResidentCredential;
class WebAuthnRemoveResidentCredentialDefaultTypeInternal;
extern WebAuthnRemoveResidentCredentialDefaultTypeInternal _WebAuthnRemoveResidentCredential_default_instance_;
}  // namespace webauthn
}  // namespace messages
}  // namespace trezor
}  // namespace hw
namespace google {
namespace protobuf {
template<> ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential* Arena::CreateMaybeMessage<::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential>(Arena*);
template<> ::hw::trezor::messages::webauthn::WebAuthnCredentials* Arena::CreateMaybeMessage<::hw::trezor::messages::webauthn::WebAuthnCredentials>(Arena*);
template<> ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* Arena::CreateMaybeMessage<::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential>(Arena*);
template<> ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials* Arena::CreateMaybeMessage<::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials>(Arena*);
template<> ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential* Arena::CreateMaybeMessage<::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace hw {
namespace trezor {
namespace messages {
namespace webauthn {

// ===================================================================

class WebAuthnListResidentCredentials final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials) */ {
 public:
  WebAuthnListResidentCredentials();
  virtual ~WebAuthnListResidentCredentials();

  WebAuthnListResidentCredentials(const WebAuthnListResidentCredentials& from);

  inline WebAuthnListResidentCredentials& operator=(const WebAuthnListResidentCredentials& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WebAuthnListResidentCredentials(WebAuthnListResidentCredentials&& from) noexcept
    : WebAuthnListResidentCredentials() {
    *this = ::std::move(from);
  }

  inline WebAuthnListResidentCredentials& operator=(WebAuthnListResidentCredentials&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WebAuthnListResidentCredentials& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WebAuthnListResidentCredentials* internal_default_instance() {
    return reinterpret_cast<const WebAuthnListResidentCredentials*>(
               &_WebAuthnListResidentCredentials_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WebAuthnListResidentCredentials* other);
  friend void swap(WebAuthnListResidentCredentials& a, WebAuthnListResidentCredentials& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WebAuthnListResidentCredentials* New() const final {
    return CreateMaybeMessage<WebAuthnListResidentCredentials>(nullptr);
  }

  WebAuthnListResidentCredentials* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WebAuthnListResidentCredentials>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WebAuthnListResidentCredentials& from);
  void MergeFrom(const WebAuthnListResidentCredentials& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WebAuthnListResidentCredentials* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2dwebauthn_2eproto;
};
// -------------------------------------------------------------------

class WebAuthnAddResidentCredential final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential) */ {
 public:
  WebAuthnAddResidentCredential();
  virtual ~WebAuthnAddResidentCredential();

  WebAuthnAddResidentCredential(const WebAuthnAddResidentCredential& from);

  inline WebAuthnAddResidentCredential& operator=(const WebAuthnAddResidentCredential& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WebAuthnAddResidentCredential(WebAuthnAddResidentCredential&& from) noexcept
    : WebAuthnAddResidentCredential() {
    *this = ::std::move(from);
  }

  inline WebAuthnAddResidentCredential& operator=(WebAuthnAddResidentCredential&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WebAuthnAddResidentCredential& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WebAuthnAddResidentCredential* internal_default_instance() {
    return reinterpret_cast<const WebAuthnAddResidentCredential*>(
               &_WebAuthnAddResidentCredential_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(WebAuthnAddResidentCredential* other);
  friend void swap(WebAuthnAddResidentCredential& a, WebAuthnAddResidentCredential& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WebAuthnAddResidentCredential* New() const final {
    return CreateMaybeMessage<WebAuthnAddResidentCredential>(nullptr);
  }

  WebAuthnAddResidentCredential* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WebAuthnAddResidentCredential>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WebAuthnAddResidentCredential& from);
  void MergeFrom(const WebAuthnAddResidentCredential& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WebAuthnAddResidentCredential* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes credential_id = 1;
  bool has_credential_id() const;
  void clear_credential_id();
  static const int kCredentialIdFieldNumber = 1;
  const ::std::string& credential_id() const;
  void set_credential_id(const ::std::string& value);
  #if LANG_CXX11
  void set_credential_id(::std::string&& value);
  #endif
  void set_credential_id(const char* value);
  void set_credential_id(const void* value, size_t size);
  ::std::string* mutable_credential_id();
  ::std::string* release_credential_id();
  void set_allocated_credential_id(::std::string* credential_id);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr credential_id_;
  friend struct ::TableStruct_messages_2dwebauthn_2eproto;
};
// -------------------------------------------------------------------

class WebAuthnRemoveResidentCredential final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential) */ {
 public:
  WebAuthnRemoveResidentCredential();
  virtual ~WebAuthnRemoveResidentCredential();

  WebAuthnRemoveResidentCredential(const WebAuthnRemoveResidentCredential& from);

  inline WebAuthnRemoveResidentCredential& operator=(const WebAuthnRemoveResidentCredential& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WebAuthnRemoveResidentCredential(WebAuthnRemoveResidentCredential&& from) noexcept
    : WebAuthnRemoveResidentCredential() {
    *this = ::std::move(from);
  }

  inline WebAuthnRemoveResidentCredential& operator=(WebAuthnRemoveResidentCredential&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WebAuthnRemoveResidentCredential& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WebAuthnRemoveResidentCredential* internal_default_instance() {
    return reinterpret_cast<const WebAuthnRemoveResidentCredential*>(
               &_WebAuthnRemoveResidentCredential_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(WebAuthnRemoveResidentCredential* other);
  friend void swap(WebAuthnRemoveResidentCredential& a, WebAuthnRemoveResidentCredential& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WebAuthnRemoveResidentCredential* New() const final {
    return CreateMaybeMessage<WebAuthnRemoveResidentCredential>(nullptr);
  }

  WebAuthnRemoveResidentCredential* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WebAuthnRemoveResidentCredential>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WebAuthnRemoveResidentCredential& from);
  void MergeFrom(const WebAuthnRemoveResidentCredential& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WebAuthnRemoveResidentCredential* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 index = 1;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 index_;
  friend struct ::TableStruct_messages_2dwebauthn_2eproto;
};
// -------------------------------------------------------------------

class WebAuthnCredentials_WebAuthnCredential final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential) */ {
 public:
  WebAuthnCredentials_WebAuthnCredential();
  virtual ~WebAuthnCredentials_WebAuthnCredential();

  WebAuthnCredentials_WebAuthnCredential(const WebAuthnCredentials_WebAuthnCredential& from);

  inline WebAuthnCredentials_WebAuthnCredential& operator=(const WebAuthnCredentials_WebAuthnCredential& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WebAuthnCredentials_WebAuthnCredential(WebAuthnCredentials_WebAuthnCredential&& from) noexcept
    : WebAuthnCredentials_WebAuthnCredential() {
    *this = ::std::move(from);
  }

  inline WebAuthnCredentials_WebAuthnCredential& operator=(WebAuthnCredentials_WebAuthnCredential&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WebAuthnCredentials_WebAuthnCredential& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WebAuthnCredentials_WebAuthnCredential* internal_default_instance() {
    return reinterpret_cast<const WebAuthnCredentials_WebAuthnCredential*>(
               &_WebAuthnCredentials_WebAuthnCredential_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(WebAuthnCredentials_WebAuthnCredential* other);
  friend void swap(WebAuthnCredentials_WebAuthnCredential& a, WebAuthnCredentials_WebAuthnCredential& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WebAuthnCredentials_WebAuthnCredential* New() const final {
    return CreateMaybeMessage<WebAuthnCredentials_WebAuthnCredential>(nullptr);
  }

  WebAuthnCredentials_WebAuthnCredential* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WebAuthnCredentials_WebAuthnCredential>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WebAuthnCredentials_WebAuthnCredential& from);
  void MergeFrom(const WebAuthnCredentials_WebAuthnCredential& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WebAuthnCredentials_WebAuthnCredential* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string rp_id = 3;
  bool has_rp_id() const;
  void clear_rp_id();
  static const int kRpIdFieldNumber = 3;
  const ::std::string& rp_id() const;
  void set_rp_id(const ::std::string& value);
  #if LANG_CXX11
  void set_rp_id(::std::string&& value);
  #endif
  void set_rp_id(const char* value);
  void set_rp_id(const char* value, size_t size);
  ::std::string* mutable_rp_id();
  ::std::string* release_rp_id();
  void set_allocated_rp_id(::std::string* rp_id);

  // optional string rp_name = 4;
  bool has_rp_name() const;
  void clear_rp_name();
  static const int kRpNameFieldNumber = 4;
  const ::std::string& rp_name() const;
  void set_rp_name(const ::std::string& value);
  #if LANG_CXX11
  void set_rp_name(::std::string&& value);
  #endif
  void set_rp_name(const char* value);
  void set_rp_name(const char* value, size_t size);
  ::std::string* mutable_rp_name();
  ::std::string* release_rp_name();
  void set_allocated_rp_name(::std::string* rp_name);

  // optional bytes user_id = 5;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 5;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  #if LANG_CXX11
  void set_user_id(::std::string&& value);
  #endif
  void set_user_id(const char* value);
  void set_user_id(const void* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // optional string user_name = 6;
  bool has_user_name() const;
  void clear_user_name();
  static const int kUserNameFieldNumber = 6;
  const ::std::string& user_name() const;
  void set_user_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_name(::std::string&& value);
  #endif
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  ::std::string* mutable_user_name();
  ::std::string* release_user_name();
  void set_allocated_user_name(::std::string* user_name);

  // optional string user_display_name = 7;
  bool has_user_display_name() const;
  void clear_user_display_name();
  static const int kUserDisplayNameFieldNumber = 7;
  const ::std::string& user_display_name() const;
  void set_user_display_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_display_name(::std::string&& value);
  #endif
  void set_user_display_name(const char* value);
  void set_user_display_name(const char* value, size_t size);
  ::std::string* mutable_user_display_name();
  ::std::string* release_user_display_name();
  void set_allocated_user_display_name(::std::string* user_display_name);

  // optional uint32 index = 1;
  bool has_index() const;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // optional uint32 creation_time = 8;
  bool has_creation_time() const;
  void clear_creation_time();
  static const int kCreationTimeFieldNumber = 8;
  ::google::protobuf::uint32 creation_time() const;
  void set_creation_time(::google::protobuf::uint32 value);

  // optional bool hmac_secret = 9;
  bool has_hmac_secret() const;
  void clear_hmac_secret();
  static const int kHmacSecretFieldNumber = 9;
  bool hmac_secret() const;
  void set_hmac_secret(bool value);

  // optional bool use_sign_count = 10;
  bool has_use_sign_count() const;
  void clear_use_sign_count();
  static const int kUseSignCountFieldNumber = 10;
  bool use_sign_count() const;
  void set_use_sign_count(bool value);

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr rp_id_;
  ::google::protobuf::internal::ArenaStringPtr rp_name_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr user_display_name_;
  ::google::protobuf::uint32 index_;
  ::google::protobuf::uint32 creation_time_;
  bool hmac_secret_;
  bool use_sign_count_;
  friend struct ::TableStruct_messages_2dwebauthn_2eproto;
};
// -------------------------------------------------------------------

class WebAuthnCredentials final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hw.trezor.messages.webauthn.WebAuthnCredentials) */ {
 public:
  WebAuthnCredentials();
  virtual ~WebAuthnCredentials();

  WebAuthnCredentials(const WebAuthnCredentials& from);

  inline WebAuthnCredentials& operator=(const WebAuthnCredentials& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WebAuthnCredentials(WebAuthnCredentials&& from) noexcept
    : WebAuthnCredentials() {
    *this = ::std::move(from);
  }

  inline WebAuthnCredentials& operator=(WebAuthnCredentials&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WebAuthnCredentials& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WebAuthnCredentials* internal_default_instance() {
    return reinterpret_cast<const WebAuthnCredentials*>(
               &_WebAuthnCredentials_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(WebAuthnCredentials* other);
  friend void swap(WebAuthnCredentials& a, WebAuthnCredentials& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WebAuthnCredentials* New() const final {
    return CreateMaybeMessage<WebAuthnCredentials>(nullptr);
  }

  WebAuthnCredentials* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WebAuthnCredentials>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WebAuthnCredentials& from);
  void MergeFrom(const WebAuthnCredentials& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WebAuthnCredentials* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef WebAuthnCredentials_WebAuthnCredential WebAuthnCredential;

  // accessors -------------------------------------------------------

  // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
  int credentials_size() const;
  void clear_credentials();
  static const int kCredentialsFieldNumber = 1;
  ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* mutable_credentials(int index);
  ::google::protobuf::RepeatedPtrField< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >*
      mutable_credentials();
  const ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential& credentials(int index) const;
  ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* add_credentials();
  const ::google::protobuf::RepeatedPtrField< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >&
      credentials() const;

  // @@protoc_insertion_point(class_scope:hw.trezor.messages.webauthn.WebAuthnCredentials)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential > credentials_;
  friend struct ::TableStruct_messages_2dwebauthn_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WebAuthnListResidentCredentials

// -------------------------------------------------------------------

// WebAuthnAddResidentCredential

// optional bytes credential_id = 1;
inline bool WebAuthnAddResidentCredential::has_credential_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WebAuthnAddResidentCredential::clear_credential_id() {
  credential_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& WebAuthnAddResidentCredential::credential_id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
  return credential_id_.GetNoArena();
}
inline void WebAuthnAddResidentCredential::set_credential_id(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  credential_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
}
#if LANG_CXX11
inline void WebAuthnAddResidentCredential::set_credential_id(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  credential_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
}
#endif
inline void WebAuthnAddResidentCredential::set_credential_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  credential_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
}
inline void WebAuthnAddResidentCredential::set_credential_id(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  credential_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
}
inline ::std::string* WebAuthnAddResidentCredential::mutable_credential_id() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
  return credential_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnAddResidentCredential::release_credential_id() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
  if (!has_credential_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return credential_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnAddResidentCredential::set_allocated_credential_id(::std::string* credential_id) {
  if (credential_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  credential_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), credential_id);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential.credential_id)
}

// -------------------------------------------------------------------

// WebAuthnRemoveResidentCredential

// optional uint32 index = 1;
inline bool WebAuthnRemoveResidentCredential::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WebAuthnRemoveResidentCredential::clear_index() {
  index_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::uint32 WebAuthnRemoveResidentCredential::index() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential.index)
  return index_;
}
inline void WebAuthnRemoveResidentCredential::set_index(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  index_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential.index)
}

// -------------------------------------------------------------------

// WebAuthnCredentials_WebAuthnCredential

// optional uint32 index = 1;
inline bool WebAuthnCredentials_WebAuthnCredential::has_index() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_index() {
  index_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::uint32 WebAuthnCredentials_WebAuthnCredential::index() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.index)
  return index_;
}
inline void WebAuthnCredentials_WebAuthnCredential::set_index(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  index_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.index)
}

// optional bytes id = 2;
inline bool WebAuthnCredentials_WebAuthnCredential::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
  return id_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_id(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_id(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_id(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_id() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_id() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
  if (!has_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_id(::std::string* id) {
  if (id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.id)
}

// optional string rp_id = 3;
inline bool WebAuthnCredentials_WebAuthnCredential::has_rp_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_rp_id() {
  rp_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::rp_id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
  return rp_id_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_id(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  rp_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_id(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  rp_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  rp_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_id(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  rp_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_rp_id() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
  return rp_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_rp_id() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
  if (!has_rp_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return rp_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_rp_id(::std::string* rp_id) {
  if (rp_id != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  rp_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rp_id);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id)
}

// optional string rp_name = 4;
inline bool WebAuthnCredentials_WebAuthnCredential::has_rp_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_rp_name() {
  rp_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::rp_name() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
  return rp_name_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  rp_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  rp_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  rp_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_rp_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  rp_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_rp_name() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
  return rp_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_rp_name() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
  if (!has_rp_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return rp_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_rp_name(::std::string* rp_name) {
  if (rp_name != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  rp_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rp_name);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name)
}

// optional bytes user_id = 5;
inline bool WebAuthnCredentials_WebAuthnCredential::has_user_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::user_id() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
  return user_id_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_id(const ::std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_user_id(::std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  user_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_id(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000008u;
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_user_id() {
  _has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_user_id() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
  if (!has_user_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return user_id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_user_id(::std::string* user_id) {
  if (user_id != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_id)
}

// optional string user_name = 6;
inline bool WebAuthnCredentials_WebAuthnCredential::has_user_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::user_name() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
  return user_name_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_user_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000010u;
  user_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000010u;
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000010u;
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_user_name() {
  _has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_user_name() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
  if (!has_user_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return user_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_user_name(::std::string* user_name) {
  if (user_name != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name)
}

// optional string user_display_name = 7;
inline bool WebAuthnCredentials_WebAuthnCredential::has_user_display_name() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_user_display_name() {
  user_display_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000020u;
}
inline const ::std::string& WebAuthnCredentials_WebAuthnCredential::user_display_name() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
  return user_display_name_.GetNoArena();
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_display_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  user_display_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
}
#if LANG_CXX11
inline void WebAuthnCredentials_WebAuthnCredential::set_user_display_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000020u;
  user_display_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
}
#endif
inline void WebAuthnCredentials_WebAuthnCredential::set_user_display_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000020u;
  user_display_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
}
inline void WebAuthnCredentials_WebAuthnCredential::set_user_display_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000020u;
  user_display_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::mutable_user_display_name() {
  _has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
  return user_display_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WebAuthnCredentials_WebAuthnCredential::release_user_display_name() {
  // @@protoc_insertion_point(field_release:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
  if (!has_user_display_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return user_display_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WebAuthnCredentials_WebAuthnCredential::set_allocated_user_display_name(::std::string* user_display_name) {
  if (user_display_name != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  user_display_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_display_name);
  // @@protoc_insertion_point(field_set_allocated:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name)
}

// optional uint32 creation_time = 8;
inline bool WebAuthnCredentials_WebAuthnCredential::has_creation_time() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_creation_time() {
  creation_time_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::google::protobuf::uint32 WebAuthnCredentials_WebAuthnCredential::creation_time() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.creation_time)
  return creation_time_;
}
inline void WebAuthnCredentials_WebAuthnCredential::set_creation_time(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  creation_time_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.creation_time)
}

// optional bool hmac_secret = 9;
inline bool WebAuthnCredentials_WebAuthnCredential::has_hmac_secret() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_hmac_secret() {
  hmac_secret_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool WebAuthnCredentials_WebAuthnCredential::hmac_secret() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.hmac_secret)
  return hmac_secret_;
}
inline void WebAuthnCredentials_WebAuthnCredential::set_hmac_secret(bool value) {
  _has_bits_[0] |= 0x00000100u;
  hmac_secret_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.hmac_secret)
}

// optional bool use_sign_count = 10;
inline bool WebAuthnCredentials_WebAuthnCredential::has_use_sign_count() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void WebAuthnCredentials_WebAuthnCredential::clear_use_sign_count() {
  use_sign_count_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool WebAuthnCredentials_WebAuthnCredential::use_sign_count() const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.use_sign_count)
  return use_sign_count_;
}
inline void WebAuthnCredentials_WebAuthnCredential::set_use_sign_count(bool value) {
  _has_bits_[0] |= 0x00000200u;
  use_sign_count_ = value;
  // @@protoc_insertion_point(field_set:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.use_sign_count)
}

// -------------------------------------------------------------------

// WebAuthnCredentials

// repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
inline int WebAuthnCredentials::credentials_size() const {
  return credentials_.size();
}
inline void WebAuthnCredentials::clear_credentials() {
  credentials_.Clear();
}
inline ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* WebAuthnCredentials::mutable_credentials(int index) {
  // @@protoc_insertion_point(field_mutable:hw.trezor.messages.webauthn.WebAuthnCredentials.credentials)
  return credentials_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >*
WebAuthnCredentials::mutable_credentials() {
  // @@protoc_insertion_point(field_mutable_list:hw.trezor.messages.webauthn.WebAuthnCredentials.credentials)
  return &credentials_;
}
inline const ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential& WebAuthnCredentials::credentials(int index) const {
  // @@protoc_insertion_point(field_get:hw.trezor.messages.webauthn.WebAuthnCredentials.credentials)
  return credentials_.Get(index);
}
inline ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* WebAuthnCredentials::add_credentials() {
  // @@protoc_insertion_point(field_add:hw.trezor.messages.webauthn.WebAuthnCredentials.credentials)
  return credentials_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >&
WebAuthnCredentials::credentials() const {
  // @@protoc_insertion_point(field_list:hw.trezor.messages.webauthn.WebAuthnCredentials.credentials)
  return credentials_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace webauthn
}  // namespace messages
}  // namespace trezor
}  // namespace hw

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_messages_2dwebauthn_2eproto
