// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages-webauthn.proto

#include "messages-webauthn.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_messages_2dwebauthn_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto;
namespace hw {
namespace trezor {
namespace messages {
namespace webauthn {
class WebAuthnListResidentCredentialsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WebAuthnListResidentCredentials> _instance;
} _WebAuthnListResidentCredentials_default_instance_;
class WebAuthnAddResidentCredentialDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WebAuthnAddResidentCredential> _instance;
} _WebAuthnAddResidentCredential_default_instance_;
class WebAuthnRemoveResidentCredentialDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WebAuthnRemoveResidentCredential> _instance;
} _WebAuthnRemoveResidentCredential_default_instance_;
class WebAuthnCredentials_WebAuthnCredentialDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WebAuthnCredentials_WebAuthnCredential> _instance;
} _WebAuthnCredentials_WebAuthnCredential_default_instance_;
class WebAuthnCredentialsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WebAuthnCredentials> _instance;
} _WebAuthnCredentials_default_instance_;
}  // namespace webauthn
}  // namespace messages
}  // namespace trezor
}  // namespace hw
static void InitDefaultsWebAuthnListResidentCredentials_messages_2dwebauthn_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hw::trezor::messages::webauthn::_WebAuthnListResidentCredentials_default_instance_;
    new (ptr) ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WebAuthnListResidentCredentials_messages_2dwebauthn_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWebAuthnListResidentCredentials_messages_2dwebauthn_2eproto}, {}};

static void InitDefaultsWebAuthnAddResidentCredential_messages_2dwebauthn_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hw::trezor::messages::webauthn::_WebAuthnAddResidentCredential_default_instance_;
    new (ptr) ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WebAuthnAddResidentCredential_messages_2dwebauthn_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWebAuthnAddResidentCredential_messages_2dwebauthn_2eproto}, {}};

static void InitDefaultsWebAuthnRemoveResidentCredential_messages_2dwebauthn_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hw::trezor::messages::webauthn::_WebAuthnRemoveResidentCredential_default_instance_;
    new (ptr) ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WebAuthnRemoveResidentCredential_messages_2dwebauthn_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWebAuthnRemoveResidentCredential_messages_2dwebauthn_2eproto}, {}};

static void InitDefaultsWebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hw::trezor::messages::webauthn::_WebAuthnCredentials_WebAuthnCredential_default_instance_;
    new (ptr) ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto}, {}};

static void InitDefaultsWebAuthnCredentials_messages_2dwebauthn_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hw::trezor::messages::webauthn::_WebAuthnCredentials_default_instance_;
    new (ptr) ::hw::trezor::messages::webauthn::WebAuthnCredentials();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hw::trezor::messages::webauthn::WebAuthnCredentials::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_WebAuthnCredentials_messages_2dwebauthn_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsWebAuthnCredentials_messages_2dwebauthn_2eproto}, {
      &scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto.base,}};

void InitDefaults_messages_2dwebauthn_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_WebAuthnListResidentCredentials_messages_2dwebauthn_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WebAuthnAddResidentCredential_messages_2dwebauthn_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WebAuthnRemoveResidentCredential_messages_2dwebauthn_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WebAuthnCredentials_messages_2dwebauthn_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_messages_2dwebauthn_2eproto[5];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_messages_2dwebauthn_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_messages_2dwebauthn_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_messages_2dwebauthn_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential, credential_id_),
  0,
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential, index_),
  0,
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, index_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, id_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, rp_id_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, rp_name_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, user_id_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, user_name_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, user_display_name_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, creation_time_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, hmac_secret_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential, use_sign_count_),
  6,
  0,
  1,
  2,
  3,
  4,
  5,
  7,
  8,
  9,
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hw::trezor::messages::webauthn::WebAuthnCredentials, credentials_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials)},
  { 5, 11, sizeof(::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential)},
  { 12, 18, sizeof(::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential)},
  { 19, 34, sizeof(::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential)},
  { 44, 50, sizeof(::hw::trezor::messages::webauthn::WebAuthnCredentials)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::hw::trezor::messages::webauthn::_WebAuthnListResidentCredentials_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hw::trezor::messages::webauthn::_WebAuthnAddResidentCredential_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hw::trezor::messages::webauthn::_WebAuthnRemoveResidentCredential_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hw::trezor::messages::webauthn::_WebAuthnCredentials_WebAuthnCredential_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hw::trezor::messages::webauthn::_WebAuthnCredentials_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_messages_2dwebauthn_2eproto = {
  {}, AddDescriptors_messages_2dwebauthn_2eproto, "messages-webauthn.proto", schemas,
  file_default_instances, TableStruct_messages_2dwebauthn_2eproto::offsets,
  file_level_metadata_messages_2dwebauthn_2eproto, 5, file_level_enum_descriptors_messages_2dwebauthn_2eproto, file_level_service_descriptors_messages_2dwebauthn_2eproto,
};

const char descriptor_table_protodef_messages_2dwebauthn_2eproto[] =
  "\n\027messages-webauthn.proto\022\033hw.trezor.mes"
  "sages.webauthn\"!\n\037WebAuthnListResidentCr"
  "edentials\"6\n\035WebAuthnAddResidentCredenti"
  "al\022\025\n\rcredential_id\030\001 \001(\014\"1\n WebAuthnRem"
  "oveResidentCredential\022\r\n\005index\030\001 \001(\r\"\304\002\n"
  "\023WebAuthnCredentials\022X\n\013credentials\030\001 \003("
  "\0132C.hw.trezor.messages.webauthn.WebAuthn"
  "Credentials.WebAuthnCredential\032\322\001\n\022WebAu"
  "thnCredential\022\r\n\005index\030\001 \001(\r\022\n\n\002id\030\002 \001(\014"
  "\022\r\n\005rp_id\030\003 \001(\t\022\017\n\007rp_name\030\004 \001(\t\022\017\n\007user"
  "_id\030\005 \001(\014\022\021\n\tuser_name\030\006 \001(\t\022\031\n\021user_dis"
  "play_name\030\007 \001(\t\022\025\n\rcreation_time\030\010 \001(\r\022\023"
  "\n\013hmac_secret\030\t \001(\010\022\026\n\016use_sign_count\030\n "
  "\001(\010B<\n#com.satoshilabs.trezor.lib.protob"
  "ufB\025TrezorMessageWebAuthn"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_messages_2dwebauthn_2eproto = {
  false, InitDefaults_messages_2dwebauthn_2eproto, 
  descriptor_table_protodef_messages_2dwebauthn_2eproto,
  "messages-webauthn.proto", &assign_descriptors_table_messages_2dwebauthn_2eproto, 585,
};

void AddDescriptors_messages_2dwebauthn_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_messages_2dwebauthn_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messages_2dwebauthn_2eproto = []() { AddDescriptors_messages_2dwebauthn_2eproto(); return true; }();
namespace hw {
namespace trezor {
namespace messages {
namespace webauthn {

// ===================================================================

void WebAuthnListResidentCredentials::InitAsDefaultInstance() {
}
class WebAuthnListResidentCredentials::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WebAuthnListResidentCredentials::WebAuthnListResidentCredentials()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
}
WebAuthnListResidentCredentials::WebAuthnListResidentCredentials(const WebAuthnListResidentCredentials& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
}

void WebAuthnListResidentCredentials::SharedCtor() {
}

WebAuthnListResidentCredentials::~WebAuthnListResidentCredentials() {
  // @@protoc_insertion_point(destructor:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  SharedDtor();
}

void WebAuthnListResidentCredentials::SharedDtor() {
}

void WebAuthnListResidentCredentials::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WebAuthnListResidentCredentials& WebAuthnListResidentCredentials::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_WebAuthnListResidentCredentials_messages_2dwebauthn_2eproto.base);
  return *internal_default_instance();
}


void WebAuthnListResidentCredentials::Clear() {
// @@protoc_insertion_point(message_clear_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* WebAuthnListResidentCredentials::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<WebAuthnListResidentCredentials*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      default: {
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool WebAuthnListResidentCredentials::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void WebAuthnListResidentCredentials::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
}

::google::protobuf::uint8* WebAuthnListResidentCredentials::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  return target;
}

size_t WebAuthnListResidentCredentials::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WebAuthnListResidentCredentials::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  GOOGLE_DCHECK_NE(&from, this);
  const WebAuthnListResidentCredentials* source =
      ::google::protobuf::DynamicCastToGenerated<WebAuthnListResidentCredentials>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
    MergeFrom(*source);
  }
}

void WebAuthnListResidentCredentials::MergeFrom(const WebAuthnListResidentCredentials& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void WebAuthnListResidentCredentials::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WebAuthnListResidentCredentials::CopyFrom(const WebAuthnListResidentCredentials& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hw.trezor.messages.webauthn.WebAuthnListResidentCredentials)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WebAuthnListResidentCredentials::IsInitialized() const {
  return true;
}

void WebAuthnListResidentCredentials::Swap(WebAuthnListResidentCredentials* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WebAuthnListResidentCredentials::InternalSwap(WebAuthnListResidentCredentials* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
}

::google::protobuf::Metadata WebAuthnListResidentCredentials::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_messages_2dwebauthn_2eproto);
  return ::file_level_metadata_messages_2dwebauthn_2eproto[kIndexInFileMessages];
}


// ===================================================================

void WebAuthnAddResidentCredential::InitAsDefaultInstance() {
}
class WebAuthnAddResidentCredential::HasBitSetters {
 public:
  static void set_has_credential_id(WebAuthnAddResidentCredential* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WebAuthnAddResidentCredential::kCredentialIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WebAuthnAddResidentCredential::WebAuthnAddResidentCredential()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
}
WebAuthnAddResidentCredential::WebAuthnAddResidentCredential(const WebAuthnAddResidentCredential& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  credential_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_credential_id()) {
    credential_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.credential_id_);
  }
  // @@protoc_insertion_point(copy_constructor:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
}

void WebAuthnAddResidentCredential::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_WebAuthnAddResidentCredential_messages_2dwebauthn_2eproto.base);
  credential_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

WebAuthnAddResidentCredential::~WebAuthnAddResidentCredential() {
  // @@protoc_insertion_point(destructor:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  SharedDtor();
}

void WebAuthnAddResidentCredential::SharedDtor() {
  credential_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void WebAuthnAddResidentCredential::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WebAuthnAddResidentCredential& WebAuthnAddResidentCredential::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_WebAuthnAddResidentCredential_messages_2dwebauthn_2eproto.base);
  return *internal_default_instance();
}


void WebAuthnAddResidentCredential::Clear() {
// @@protoc_insertion_point(message_clear_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    credential_id_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* WebAuthnAddResidentCredential::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<WebAuthnAddResidentCredential*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional bytes credential_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_credential_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool WebAuthnAddResidentCredential::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes credential_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_credential_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void WebAuthnAddResidentCredential::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bytes credential_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->credential_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
}

::google::protobuf::uint8* WebAuthnAddResidentCredential::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bytes credential_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->credential_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  return target;
}

size_t WebAuthnAddResidentCredential::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes credential_id = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->credential_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WebAuthnAddResidentCredential::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  GOOGLE_DCHECK_NE(&from, this);
  const WebAuthnAddResidentCredential* source =
      ::google::protobuf::DynamicCastToGenerated<WebAuthnAddResidentCredential>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
    MergeFrom(*source);
  }
}

void WebAuthnAddResidentCredential::MergeFrom(const WebAuthnAddResidentCredential& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_credential_id()) {
    _has_bits_[0] |= 0x00000001u;
    credential_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.credential_id_);
  }
}

void WebAuthnAddResidentCredential::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WebAuthnAddResidentCredential::CopyFrom(const WebAuthnAddResidentCredential& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hw.trezor.messages.webauthn.WebAuthnAddResidentCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WebAuthnAddResidentCredential::IsInitialized() const {
  return true;
}

void WebAuthnAddResidentCredential::Swap(WebAuthnAddResidentCredential* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WebAuthnAddResidentCredential::InternalSwap(WebAuthnAddResidentCredential* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  credential_id_.Swap(&other->credential_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata WebAuthnAddResidentCredential::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_messages_2dwebauthn_2eproto);
  return ::file_level_metadata_messages_2dwebauthn_2eproto[kIndexInFileMessages];
}


// ===================================================================

void WebAuthnRemoveResidentCredential::InitAsDefaultInstance() {
}
class WebAuthnRemoveResidentCredential::HasBitSetters {
 public:
  static void set_has_index(WebAuthnRemoveResidentCredential* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WebAuthnRemoveResidentCredential::kIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WebAuthnRemoveResidentCredential::WebAuthnRemoveResidentCredential()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
}
WebAuthnRemoveResidentCredential::WebAuthnRemoveResidentCredential(const WebAuthnRemoveResidentCredential& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  index_ = from.index_;
  // @@protoc_insertion_point(copy_constructor:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
}

void WebAuthnRemoveResidentCredential::SharedCtor() {
  index_ = 0u;
}

WebAuthnRemoveResidentCredential::~WebAuthnRemoveResidentCredential() {
  // @@protoc_insertion_point(destructor:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  SharedDtor();
}

void WebAuthnRemoveResidentCredential::SharedDtor() {
}

void WebAuthnRemoveResidentCredential::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WebAuthnRemoveResidentCredential& WebAuthnRemoveResidentCredential::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_WebAuthnRemoveResidentCredential_messages_2dwebauthn_2eproto.base);
  return *internal_default_instance();
}


void WebAuthnRemoveResidentCredential::Clear() {
// @@protoc_insertion_point(message_clear_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  index_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* WebAuthnRemoveResidentCredential::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<WebAuthnRemoveResidentCredential*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional uint32 index = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_index(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool WebAuthnRemoveResidentCredential::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_index(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void WebAuthnRemoveResidentCredential::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 index = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->index(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
}

::google::protobuf::uint8* WebAuthnRemoveResidentCredential::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 index = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->index(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  return target;
}

size_t WebAuthnRemoveResidentCredential::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint32 index = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WebAuthnRemoveResidentCredential::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  GOOGLE_DCHECK_NE(&from, this);
  const WebAuthnRemoveResidentCredential* source =
      ::google::protobuf::DynamicCastToGenerated<WebAuthnRemoveResidentCredential>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
    MergeFrom(*source);
  }
}

void WebAuthnRemoveResidentCredential::MergeFrom(const WebAuthnRemoveResidentCredential& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_index()) {
    set_index(from.index());
  }
}

void WebAuthnRemoveResidentCredential::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WebAuthnRemoveResidentCredential::CopyFrom(const WebAuthnRemoveResidentCredential& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hw.trezor.messages.webauthn.WebAuthnRemoveResidentCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WebAuthnRemoveResidentCredential::IsInitialized() const {
  return true;
}

void WebAuthnRemoveResidentCredential::Swap(WebAuthnRemoveResidentCredential* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WebAuthnRemoveResidentCredential::InternalSwap(WebAuthnRemoveResidentCredential* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(index_, other->index_);
}

::google::protobuf::Metadata WebAuthnRemoveResidentCredential::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_messages_2dwebauthn_2eproto);
  return ::file_level_metadata_messages_2dwebauthn_2eproto[kIndexInFileMessages];
}


// ===================================================================

void WebAuthnCredentials_WebAuthnCredential::InitAsDefaultInstance() {
}
class WebAuthnCredentials_WebAuthnCredential::HasBitSetters {
 public:
  static void set_has_index(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000040u;
  }
  static void set_has_id(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_rp_id(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_rp_name(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_user_id(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_user_name(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000010u;
  }
  static void set_has_user_display_name(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000020u;
  }
  static void set_has_creation_time(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000080u;
  }
  static void set_has_hmac_secret(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000100u;
  }
  static void set_has_use_sign_count(WebAuthnCredentials_WebAuthnCredential* msg) {
    msg->_has_bits_[0] |= 0x00000200u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WebAuthnCredentials_WebAuthnCredential::kIndexFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kIdFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kRpIdFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kRpNameFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kUserIdFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kUserNameFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kUserDisplayNameFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kCreationTimeFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kHmacSecretFieldNumber;
const int WebAuthnCredentials_WebAuthnCredential::kUseSignCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WebAuthnCredentials_WebAuthnCredential::WebAuthnCredentials_WebAuthnCredential()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
}
WebAuthnCredentials_WebAuthnCredential::WebAuthnCredentials_WebAuthnCredential(const WebAuthnCredentials_WebAuthnCredential& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_id()) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  rp_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_rp_id()) {
    rp_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rp_id_);
  }
  rp_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_rp_name()) {
    rp_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rp_name_);
  }
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_user_id()) {
    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_user_name()) {
    user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_name_);
  }
  user_display_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_user_display_name()) {
    user_display_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_display_name_);
  }
  ::memcpy(&index_, &from.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&use_sign_count_) -
    reinterpret_cast<char*>(&index_)) + sizeof(use_sign_count_));
  // @@protoc_insertion_point(copy_constructor:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
}

void WebAuthnCredentials_WebAuthnCredential::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto.base);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rp_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rp_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_display_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&use_sign_count_) -
      reinterpret_cast<char*>(&index_)) + sizeof(use_sign_count_));
}

WebAuthnCredentials_WebAuthnCredential::~WebAuthnCredentials_WebAuthnCredential() {
  // @@protoc_insertion_point(destructor:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  SharedDtor();
}

void WebAuthnCredentials_WebAuthnCredential::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rp_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rp_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  user_display_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void WebAuthnCredentials_WebAuthnCredential::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WebAuthnCredentials_WebAuthnCredential& WebAuthnCredentials_WebAuthnCredential::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_WebAuthnCredentials_WebAuthnCredential_messages_2dwebauthn_2eproto.base);
  return *internal_default_instance();
}


void WebAuthnCredentials_WebAuthnCredential::Clear() {
// @@protoc_insertion_point(message_clear_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      rp_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      rp_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      user_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      user_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000020u) {
      user_display_name_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 0x000000c0u) {
    ::memset(&index_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&creation_time_) -
        reinterpret_cast<char*>(&index_)) + sizeof(creation_time_));
  }
  if (cached_has_bits & 0x00000300u) {
    ::memset(&hmac_secret_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&use_sign_count_) -
        reinterpret_cast<char*>(&hmac_secret_)) + sizeof(use_sign_count_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* WebAuthnCredentials_WebAuthnCredential::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<WebAuthnCredentials_WebAuthnCredential*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional uint32 index = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_index(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bytes id = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional string rp_id = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id");
        object = msg->mutable_rp_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional string rp_name = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name");
        object = msg->mutable_rp_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional bytes user_id = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_user_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional string user_name = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name");
        object = msg->mutable_user_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional string user_display_name = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 58) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name");
        object = msg->mutable_user_display_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // optional uint32 creation_time = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        msg->set_creation_time(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool hmac_secret = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 72) goto handle_unusual;
        msg->set_hmac_secret(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool use_sign_count = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 80) goto handle_unusual;
        msg->set_use_sign_count(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool WebAuthnCredentials_WebAuthnCredential::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_index(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string rp_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rp_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->rp_id().data(), static_cast<int>(this->rp_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string rp_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rp_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->rp_name().data(), static_cast<int>(this->rp_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes user_id = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_user_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string user_name = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->user_name().data(), static_cast<int>(this->user_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string user_display_name = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (58 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_user_display_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->user_display_name().data(), static_cast<int>(this->user_display_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 creation_time = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {
          HasBitSetters::set_has_creation_time(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &creation_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool hmac_secret = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (72 & 0xFF)) {
          HasBitSetters::set_has_hmac_secret(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hmac_secret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool use_sign_count = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (80 & 0xFF)) {
          HasBitSetters::set_has_use_sign_count(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &use_sign_count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void WebAuthnCredentials_WebAuthnCredential::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 index = 1;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->index(), output);
  }

  // optional bytes id = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->id(), output);
  }

  // optional string rp_id = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rp_id().data(), static_cast<int>(this->rp_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->rp_id(), output);
  }

  // optional string rp_name = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rp_name().data(), static_cast<int>(this->rp_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->rp_name(), output);
  }

  // optional bytes user_id = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->user_id(), output);
  }

  // optional string user_name = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_name().data(), static_cast<int>(this->user_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->user_name(), output);
  }

  // optional string user_display_name = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_display_name().data(), static_cast<int>(this->user_display_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->user_display_name(), output);
  }

  // optional uint32 creation_time = 8;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->creation_time(), output);
  }

  // optional bool hmac_secret = 9;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->hmac_secret(), output);
  }

  // optional bool use_sign_count = 10;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->use_sign_count(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
}

::google::protobuf::uint8* WebAuthnCredentials_WebAuthnCredential::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 index = 1;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->index(), target);
  }

  // optional bytes id = 2;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->id(), target);
  }

  // optional string rp_id = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rp_id().data(), static_cast<int>(this->rp_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->rp_id(), target);
  }

  // optional string rp_name = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->rp_name().data(), static_cast<int>(this->rp_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.rp_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->rp_name(), target);
  }

  // optional bytes user_id = 5;
  if (cached_has_bits & 0x00000008u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->user_id(), target);
  }

  // optional string user_name = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_name().data(), static_cast<int>(this->user_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->user_name(), target);
  }

  // optional string user_display_name = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->user_display_name().data(), static_cast<int>(this->user_display_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential.user_display_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->user_display_name(), target);
  }

  // optional uint32 creation_time = 8;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->creation_time(), target);
  }

  // optional bool hmac_secret = 9;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->hmac_secret(), target);
  }

  // optional bool use_sign_count = 10;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->use_sign_count(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  return target;
}

size_t WebAuthnCredentials_WebAuthnCredential::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes id = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->id());
    }

    // optional string rp_id = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->rp_id());
    }

    // optional string rp_name = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->rp_name());
    }

    // optional bytes user_id = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->user_id());
    }

    // optional string user_name = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->user_name());
    }

    // optional string user_display_name = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->user_display_name());
    }

    // optional uint32 index = 1;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->index());
    }

    // optional uint32 creation_time = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->creation_time());
    }

  }
  if (cached_has_bits & 0x00000300u) {
    // optional bool hmac_secret = 9;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + 1;
    }

    // optional bool use_sign_count = 10;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WebAuthnCredentials_WebAuthnCredential::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  GOOGLE_DCHECK_NE(&from, this);
  const WebAuthnCredentials_WebAuthnCredential* source =
      ::google::protobuf::DynamicCastToGenerated<WebAuthnCredentials_WebAuthnCredential>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
    MergeFrom(*source);
  }
}

void WebAuthnCredentials_WebAuthnCredential::MergeFrom(const WebAuthnCredentials_WebAuthnCredential& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
    }
    if (cached_has_bits & 0x00000002u) {
      _has_bits_[0] |= 0x00000002u;
      rp_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rp_id_);
    }
    if (cached_has_bits & 0x00000004u) {
      _has_bits_[0] |= 0x00000004u;
      rp_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rp_name_);
    }
    if (cached_has_bits & 0x00000008u) {
      _has_bits_[0] |= 0x00000008u;
      user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
    }
    if (cached_has_bits & 0x00000010u) {
      _has_bits_[0] |= 0x00000010u;
      user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_name_);
    }
    if (cached_has_bits & 0x00000020u) {
      _has_bits_[0] |= 0x00000020u;
      user_display_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_display_name_);
    }
    if (cached_has_bits & 0x00000040u) {
      index_ = from.index_;
    }
    if (cached_has_bits & 0x00000080u) {
      creation_time_ = from.creation_time_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000300u) {
    if (cached_has_bits & 0x00000100u) {
      hmac_secret_ = from.hmac_secret_;
    }
    if (cached_has_bits & 0x00000200u) {
      use_sign_count_ = from.use_sign_count_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void WebAuthnCredentials_WebAuthnCredential::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WebAuthnCredentials_WebAuthnCredential::CopyFrom(const WebAuthnCredentials_WebAuthnCredential& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WebAuthnCredentials_WebAuthnCredential::IsInitialized() const {
  return true;
}

void WebAuthnCredentials_WebAuthnCredential::Swap(WebAuthnCredentials_WebAuthnCredential* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WebAuthnCredentials_WebAuthnCredential::InternalSwap(WebAuthnCredentials_WebAuthnCredential* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  id_.Swap(&other->id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  rp_id_.Swap(&other->rp_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  rp_name_.Swap(&other->rp_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  user_id_.Swap(&other->user_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  user_name_.Swap(&other->user_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  user_display_name_.Swap(&other->user_display_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(index_, other->index_);
  swap(creation_time_, other->creation_time_);
  swap(hmac_secret_, other->hmac_secret_);
  swap(use_sign_count_, other->use_sign_count_);
}

::google::protobuf::Metadata WebAuthnCredentials_WebAuthnCredential::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_messages_2dwebauthn_2eproto);
  return ::file_level_metadata_messages_2dwebauthn_2eproto[kIndexInFileMessages];
}


// ===================================================================

void WebAuthnCredentials::InitAsDefaultInstance() {
}
class WebAuthnCredentials::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WebAuthnCredentials::kCredentialsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WebAuthnCredentials::WebAuthnCredentials()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hw.trezor.messages.webauthn.WebAuthnCredentials)
}
WebAuthnCredentials::WebAuthnCredentials(const WebAuthnCredentials& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      credentials_(from.credentials_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hw.trezor.messages.webauthn.WebAuthnCredentials)
}

void WebAuthnCredentials::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_WebAuthnCredentials_messages_2dwebauthn_2eproto.base);
}

WebAuthnCredentials::~WebAuthnCredentials() {
  // @@protoc_insertion_point(destructor:hw.trezor.messages.webauthn.WebAuthnCredentials)
  SharedDtor();
}

void WebAuthnCredentials::SharedDtor() {
}

void WebAuthnCredentials::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WebAuthnCredentials& WebAuthnCredentials::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_WebAuthnCredentials_messages_2dwebauthn_2eproto.base);
  return *internal_default_instance();
}


void WebAuthnCredentials::Clear() {
// @@protoc_insertion_point(message_clear_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  credentials_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* WebAuthnCredentials::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<WebAuthnCredentials*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential::_InternalParse;
          object = msg->add_credentials();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool WebAuthnCredentials::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_credentials()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hw.trezor.messages.webauthn.WebAuthnCredentials)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hw.trezor.messages.webauthn.WebAuthnCredentials)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void WebAuthnCredentials::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->credentials_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->credentials(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hw.trezor.messages.webauthn.WebAuthnCredentials)
}

::google::protobuf::uint8* WebAuthnCredentials::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->credentials_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->credentials(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hw.trezor.messages.webauthn.WebAuthnCredentials)
  return target;
}

size_t WebAuthnCredentials::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .hw.trezor.messages.webauthn.WebAuthnCredentials.WebAuthnCredential credentials = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->credentials_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->credentials(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WebAuthnCredentials::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  GOOGLE_DCHECK_NE(&from, this);
  const WebAuthnCredentials* source =
      ::google::protobuf::DynamicCastToGenerated<WebAuthnCredentials>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hw.trezor.messages.webauthn.WebAuthnCredentials)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hw.trezor.messages.webauthn.WebAuthnCredentials)
    MergeFrom(*source);
  }
}

void WebAuthnCredentials::MergeFrom(const WebAuthnCredentials& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  credentials_.MergeFrom(from.credentials_);
}

void WebAuthnCredentials::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WebAuthnCredentials::CopyFrom(const WebAuthnCredentials& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hw.trezor.messages.webauthn.WebAuthnCredentials)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WebAuthnCredentials::IsInitialized() const {
  return true;
}

void WebAuthnCredentials::Swap(WebAuthnCredentials* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WebAuthnCredentials::InternalSwap(WebAuthnCredentials* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  CastToBase(&credentials_)->InternalSwap(CastToBase(&other->credentials_));
}

::google::protobuf::Metadata WebAuthnCredentials::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_messages_2dwebauthn_2eproto);
  return ::file_level_metadata_messages_2dwebauthn_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace webauthn
}  // namespace messages
}  // namespace trezor
}  // namespace hw
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials* Arena::CreateMaybeMessage< ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials >(Arena* arena) {
  return Arena::CreateInternal< ::hw::trezor::messages::webauthn::WebAuthnListResidentCredentials >(arena);
}
template<> PROTOBUF_NOINLINE ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential* Arena::CreateMaybeMessage< ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential >(Arena* arena) {
  return Arena::CreateInternal< ::hw::trezor::messages::webauthn::WebAuthnAddResidentCredential >(arena);
}
template<> PROTOBUF_NOINLINE ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential* Arena::CreateMaybeMessage< ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential >(Arena* arena) {
  return Arena::CreateInternal< ::hw::trezor::messages::webauthn::WebAuthnRemoveResidentCredential >(arena);
}
template<> PROTOBUF_NOINLINE ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential* Arena::CreateMaybeMessage< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >(Arena* arena) {
  return Arena::CreateInternal< ::hw::trezor::messages::webauthn::WebAuthnCredentials_WebAuthnCredential >(arena);
}
template<> PROTOBUF_NOINLINE ::hw::trezor::messages::webauthn::WebAuthnCredentials* Arena::CreateMaybeMessage< ::hw::trezor::messages::webauthn::WebAuthnCredentials >(Arena* arena) {
  return Arena::CreateInternal< ::hw::trezor::messages::webauthn::WebAuthnCredentials >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
